/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int JUMP = 12;
  /** RegularExpression Id. */
  int WALK = 13;
  /** RegularExpression Id. */
  int LEAP = 14;
  /** RegularExpression Id. */
  int TURN = 15;
  /** RegularExpression Id. */
  int TURNTO = 16;
  /** RegularExpression Id. */
  int DROP = 17;
  /** RegularExpression Id. */
  int GET = 18;
  /** RegularExpression Id. */
  int GRAB = 19;
  /** RegularExpression Id. */
  int LETGO = 20;
  /** RegularExpression Id. */
  int NOP = 21;
  /** RegularExpression Id. */
  int DEFVAR = 22;
  /** RegularExpression Id. */
  int DEFPROC = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int REPEAT = 27;
  /** RegularExpression Id. */
  int TIMES = 28;
  /** RegularExpression Id. */
  int FACING = 29;
  /** RegularExpression Id. */
  int CAN = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int DIRECTION = 32;
  /** RegularExpression Id. */
  int ORIENTATION = 33;
  /** RegularExpression Id. */
  int CONDITIONAL = 34;
  /** RegularExpression Id. */
  int BALLOONS = 35;
  /** RegularExpression Id. */
  int CHIPS = 36;
  /** RegularExpression Id. */
  int VARIABLE_NAME = 37;
  /** RegularExpression Id. */
  int CONDITION = 38;
  /** RegularExpression Id. */
  int PERIOD = 39;
  /** RegularExpression Id. */
  int RPAREN = 40;
  /** RegularExpression Id. */
  int LPAREN = 41;
  /** RegularExpression Id. */
  int QUOTE = 42;
  /** RegularExpression Id. */
  int RSQUARE = 43;
  /** RegularExpression Id. */
  int LSQUARE = 44;
  /** RegularExpression Id. */
  int DOSPUNTOS = 45;
  /** RegularExpression Id. */
  int COMA = 46;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 47;
  /** RegularExpression Id. */
  int RCURLY = 48;
  /** RegularExpression Id. */
  int LCURLY = 49;
  /** RegularExpression Id. */
  int NUM = 50;
  /** RegularExpression Id. */
  int DIGIT = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"jump\"",
    "\"walk\"",
    "\"leap\"",
    "\"turn\"",
    "\"turnto\"",
    "\"drop\"",
    "\"get\"",
    "\"grab\"",
    "\"letGo\"",
    "\"nop\"",
    "\"defVar\"",
    "\"defProc\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"repeat\"",
    "\"times\"",
    "\"facing\"",
    "\"can\"",
    "\"not\"",
    "<DIRECTION>",
    "<ORIENTATION>",
    "<CONDITIONAL>",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<VARIABLE_NAME>",
    "<CONDITION>",
    "\".\"",
    "\")\"",
    "\"(\"",
    "\"\\\"\"",
    "\"]\"",
    "\"[\"",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"}\"",
    "\"{\"",
    "<NUM>",
    "<DIGIT>",
  };

}
