/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int JUMP = 12;
  /** RegularExpression Id. */
  int LEAP = 13;
  /** RegularExpression Id. */
  int TURN = 14;
  /** RegularExpression Id. */
  int TURNTO = 15;
  /** RegularExpression Id. */
  int DROP = 16;
  /** RegularExpression Id. */
  int GET = 17;
  /** RegularExpression Id. */
  int GRAB = 18;
  /** RegularExpression Id. */
  int LETGO = 19;
  /** RegularExpression Id. */
  int NOP = 20;
  /** RegularExpression Id. */
  int DEFVAR = 21;
  /** RegularExpression Id. */
  int DEFPROC = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int WHILE = 25;
  /** RegularExpression Id. */
  int REPEAT = 26;
  /** RegularExpression Id. */
  int TIMES = 27;
  /** RegularExpression Id. */
  int FACING = 28;
  /** RegularExpression Id. */
  int CAN = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int VARIABLE = 31;
  /** RegularExpression Id. */
  int INTEGER = 32;
  /** RegularExpression Id. */
  int PERIOD = 33;
  /** RegularExpression Id. */
  int RPAREN = 34;
  /** RegularExpression Id. */
  int LPAREN = 35;
  /** RegularExpression Id. */
  int QUOTE = 36;
  /** RegularExpression Id. */
  int RSQUARE = 37;
  /** RegularExpression Id. */
  int LSQUARE = 38;
  /** RegularExpression Id. */
  int DOSPUNTOS = 39;
  /** RegularExpression Id. */
  int COMA = 40;
  /** RegularExpression Id. */
  int BALLOONS = 41;
  /** RegularExpression Id. */
  int CHIPS = 42;
  /** RegularExpression Id. */
  int NUM = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Move\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"jump\"",
    "\"leap\"",
    "\"turn\"",
    "\"turnto\"",
    "\"drop\"",
    "\"get\"",
    "\"grab\"",
    "\"letGo\"",
    "\"nop\"",
    "\"defVar\"",
    "\"defProc\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"repeat\"",
    "\"times\"",
    "\"facing\"",
    "\"can\"",
    "\"not\"",
    "<VARIABLE>",
    "<INTEGER>",
    "\".\"",
    "\")\"",
    "\"(\"",
    "\"\\\"\"",
    "\"]\"",
    "\"[\"",
    "\":\"",
    "\",\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "\";\"",
  };

}
